name: instagram_dbt
version: 1.0.0
config-version: 2

profile: instagram_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

seeds:
  +database: instagram

models:
  +database: instagram
  +materialized: view

  instagram_dbt:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    analysis:
      +schema: analysis
      +materialized: view